// Common nicknames and abbreviations for colleges
// Maps alias -> partial match string(s) that appear in official name

export const SCHOOL_ALIASES: Record<string, string[]> = {
  // UC System
  'ucla': ['university of california-los angeles'],
  'ucb': ['university of california-berkeley'],
  'uc berkeley': ['university of california-berkeley'],
  'cal': ['university of california-berkeley'],
  'ucsb': ['university of california-santa barbara'],
  'ucsd': ['university of california-san diego'],
  'uci': ['university of california-irvine'],
  'ucd': ['university of california-davis'],
  'uc davis': ['university of california-davis'],
  'ucsc': ['university of california-santa cruz'],
  'ucr': ['university of california-riverside'],
  'ucm': ['university of california-merced'],
  
  // Ivy League
  'harvard': ['harvard university'],
  'yale': ['yale university'],
  'princeton': ['princeton university'],
  'columbia': ['columbia university in the city of new york'],
  'penn': ['university of pennsylvania'],
  'upenn': ['university of pennsylvania'],
  'dartmouth': ['dartmouth college'],
  'brown': ['brown university'],
  'cornell': ['cornell university'],
  
  // Big State Schools
  'ut austin': ['university of texas at austin'],
  'ut': ['university of texas at austin'],
  'texas': ['university of texas at austin'],
  'umich': ['university of michigan-ann arbor'],
  'michigan': ['university of michigan-ann arbor'],
  'unc': ['university of north carolina at chapel hill'],
  'chapel hill': ['university of north carolina at chapel hill'],
  'uva': ['university of virginia'],
  'usc': ['university of southern california'],
  'osu': ['ohio state university'],
  'ohio state': ['ohio state university'],
  'psu': ['pennsylvania state university'],
  'penn state': ['pennsylvania state university'],
  'msu': ['michigan state university'],
  'fsu': ['florida state university'],
  'uf': ['university of florida'],
  'gators': ['university of florida'],
  'uga': ['university of georgia'],
  'tamu': ['texas a & m university'],
  'texas a&m': ['texas a & m university'],
  'uw': ['university of washington-seattle', 'university of wisconsin-madison'],
  'uw madison': ['university of wisconsin-madison'],
  'uw seattle': ['university of washington-seattle'],
  'cu boulder': ['university of colorado boulder'],
  'colorado': ['university of colorado boulder'],
  'arizona state': ['arizona state university'],
  'asu': ['arizona state university'],
  'uiuc': ['university of illinois urbana-champaign'],
  'illinois': ['university of illinois urbana-champaign'],
  'purdue': ['purdue university'],
  'indiana': ['indiana university-bloomington'],
  'iu': ['indiana university-bloomington'],
  'rutgers': ['rutgers university'],
  
  // Elite Privates
  'mit': ['massachusetts institute of technology'],
  'stanford': ['stanford university'],
  'duke': ['duke university'],
  'northwestern': ['northwestern university'],
  'notre dame': ['university of notre dame'],
  'vandy': ['vanderbilt university'],
  'vanderbilt': ['vanderbilt university'],
  'rice': ['rice university'],
  'emory': ['emory university'],
  'wustl': ['washington university in st louis'],
  'wash u': ['washington university in st louis'],
  'jhu': ['johns hopkins university'],
  'johns hopkins': ['johns hopkins university'],
  'cmu': ['carnegie mellon university'],
  'carnegie mellon': ['carnegie mellon university'],
  'georgetown': ['georgetown university'],
  'nyu': ['new york university'],
  'bu': ['boston university'],
  'bc': ['boston college'],
  'tufts': ['tufts university'],
  'tulane': ['tulane university'],
  
  // Tech Schools
  'caltech': ['california institute of technology'],
  'georgia tech': ['georgia institute of technology'],
  'gt': ['georgia institute of technology'],
  'rpi': ['rensselaer polytechnic institute'],
  'vt': ['virginia polytechnic institute', 'virginia tech'],
  'virginia tech': ['virginia polytechnic institute'],
  
  // LACs
  'williams': ['williams college'],
  'amherst': ['amherst college'],
  'swarthmore': ['swarthmore college'],
  'wellesley': ['wellesley college'],
  'pomona': ['pomona college'],
  'bowdoin': ['bowdoin college'],
  'middlebury': ['middlebury college'],
  'carleton': ['carleton college'],
  'claremont mckenna': ['claremont mckenna college'],
  'cmc': ['claremont mckenna college'],
  
  // CSU System
  'sf state': ['san francisco state university'],
  'sdsu': ['san diego state university'],
  'sjsu': ['san jose state university'],
  'cal poly': ['california polytechnic state university'],
  'cal poly slo': ['california polytechnic state university-san luis obispo'],
  'cal poly pomona': ['california state polytechnic university-pomona'],
  
  // SUNY System
  'suny buffalo': ['university at buffalo'],
  'ub': ['university at buffalo'],
  'suny stony brook': ['stony brook university'],
  'stony brook': ['stony brook university'],
  'suny binghamton': ['binghamton university'],
  'binghamton': ['binghamton university'],
  
  // Other notable
  'uconn': ['university of connecticut'],
  'uri': ['university of rhode island'],
  'unh': ['university of new hampshire'],
  'umass': ['university of massachusetts'],
  'umd': ['university of maryland'],
  'maryland': ['university of maryland'],
  'pitt': ['university of pittsburgh'],
  'temple': ['temple university'],
  'drexel': ['drexel university'],
  'villanova': ['villanova university'],
  'wake forest': ['wake forest university'],
  'wake': ['wake forest university'],
  'miami': ['university of miami', 'miami university-oxford'],
  'um': ['university of miami'],
  'fiu': ['florida international university'],
  'ucf': ['university of central florida'],
  'usf': ['university of south florida'],
  'lsu': ['louisiana state university'],
  'ole miss': ['university of mississippi'],
  'auburn': ['auburn university'],
  'bama': ['university of alabama'],
  'alabama': ['university of alabama'],
  'tennessee': ['university of tennessee'],
  'ut knoxville': ['university of tennessee-knoxville'],
  'kentucky': ['university of kentucky'],
  'uk': ['university of kentucky'],
  'louisville': ['university of louisville'],
  'kansas': ['university of kansas'],
  'ku': ['university of kansas'],
  'ksu': ['kansas state university'],
  'mizzou': ['university of missouri'],
  'missouri': ['university of missouri'],
  'iowa': ['university of iowa'],
  'iowa state': ['iowa state university'],
  'nebraska': ['university of nebraska'],
  'minnesota': ['university of minnesota'],
  'gophers': ['university of minnesota'],
  'oregon': ['university of oregon'],
  'ducks': ['university of oregon'],
  'oregon state': ['oregon state university'],
  'washington state': ['washington state university'],
  'wsu': ['washington state university'],
  'usc upstate': ['university of south carolina'],
  'sc': ['university of south carolina'],
  'clemson': ['clemson university'],
  'nc state': ['north carolina state university'],
  'ncsu': ['north carolina state university'],
};

// Returns school names that match the given alias (case-insensitive)
export function getAliasMatches(query: string): string[] {
  const lowerQuery = query.toLowerCase().trim();
  return SCHOOL_ALIASES[lowerQuery] || [];
}
